# Multiple Linear Regression

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv("50_startups.csv")

In [10]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [11]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [12]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

## Encoding categorical data

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [3])], remainder="passthrough")

X = ct.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=26)

## Training the Multiple Linear Regression model on the Training set

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
regressor = LinearRegression()

In [24]:
regressor.fit(X_train, Y_train)

LinearRegression()

In [30]:
regressor.coef_

array([ 1.50877043e+03, -1.55750167e+01, -1.49319541e+03,  7.55652007e-01,
        1.19475011e-02,  3.42174219e-02])

In [31]:
regressor.intercept_

48697.94214214767

## Predicting the Test set results

In [25]:
Y_pred = regressor.predict(X_test)

In [29]:
np.concatenate((Y_test.reshape(len(Y_test),1), Y_pred.reshape(len(Y_test),1)), axis=1)

array([[191050.39      , 179797.65693028],
       [ 69758.98      ,  61659.47058579],
       [146121.95      , 134855.81071745],
       [132602.65      , 149965.27842634],
       [ 65200.33      ,  69784.45391126],
       [156991.12      , 160466.50748403],
       [ 96778.92      ,  99192.01114076],
       [155752.6       , 159963.35611178],
       [149759.96      , 155139.09142861],
       [ 49490.75      ,  61226.60225098],
       [152211.77      , 150732.36712083],
       [ 14681.4       ,  53150.08230715],
       [192261.83      , 189930.02376299]])